package BoyosPlace::Model::Database;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'BoyosPlace::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=boyosplace_dev',
        user => 'boyosplace_dev',
        password => 'boyo!dev',
    }
);

=head1 NAME

BoyosPlace::Model::Database - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<BoyosPlace>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<BoyosPlace::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR



=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
